### ISSUE TITLE
Moons/sub-planets break the app [BUG]

### ISSUE THREAD

**Issue by PatchedInfinities** [DaIsimsiz/planetDefs-Builder#2]
**Describe the bug**
Upon making a planetDefs.xml without the help of the editor and adding a moon, trying to check the moon's settings will cause a "System.ArgumentOutOfRangeException" error.

**To Reproduce**
1. Create a planetDefs.xml file with a system containing a moon, or use the default.
2. Import the file to the editor/builder
3. Open the planet's properties, that should contain a moon.
4. System.ArgumentOutOfRangeException

**Expected behavior**
Treating sub-planets/moons as either a planet or a moon.

**Screenshots**
![image](https://github.com/DaIsimsiz/planetDefs-Builder/assets/165608774/03b0c5fa-ba38-4c21-9084-2e68e6d46ec3)

**Additional context**
None.

**Comment by DaIsimsiz** [comment]
Can you send me the planetDefs.xml you used for this?

**Comment by DaIsimsiz** [comment]
It took some effort, but I've found and fixed the code! The root of the problem was some typos, of all things...
Thank you so much for your bug report!!
