### ISSUE TITLE
not being able to import binary stars[BUG]

### ISSUE THREAD

**Issue by erloen** [DaIsimsiz/planetDefs-Builder#5]
**Describe the bug**
not being able to import binary system since it will just end with stars named null star wich you cant edit

**To Reproduce**
i put the reproduction into the video
**Expected behavior**
stars get anmed

https://github.com/DaIsimsiz/planetDefs-Builder/assets/172145093/eaaa3b9d-2cb5-4b30-b2b0-eceec382b4f4

 named null wich you cant edit

**Comment by DaIsimsiz** [comment]
Can you provide a planetDefs.xml for easier debugging?
